### ISSUE TITLE
implement logging

### ISSUE THREAD

**Issue by lubomirkamensky** [dwhacademy/demoproject#6]

**Comment by lubomirkamensky** [comment]
execution of each procedure will be logged

**Comment by lubomirkamensky** [comment]
pending merge request

**Comment by swiernia** [comment]
after merging the changes in the code, this issue should be re-assigned to an analyst for review - deas github have this kind of capability?

**Comment by lubomirkamensky** [comment]
assigned to analyst for review

**Comment by swiernia** [comment]
I know the issue can be re-assiged but ideally the status should be different to know which issues are 'under review' or in 'testing' phase. Perhaps there are apps that can track multiple statuses, not only 'Open' and 'Closed'

**Comment by lubomirkamensky** [comment]
the status can be only open or closed, perhaps utilize the kanban
https://github.com/dwhacademy/demoproject/projects/1


ne 8. 9. 2019 v 13:40 odesílatel Grzegorz Świerniak <
notifications@github.com> napsal:
